version: "3.7"

services:
  nginx:
    build: docker/nginx
    restart: on-failure
    volumes:
      # this will mount the api folder which contains the code to the docker container
      - ./app:/var/www/app
      # this will mount the nginx logs so that you can check the logs for errors,
      # without logging into the container
      - ./var/logs/nginx/:/var/log/nginx
      # this will create the server config to serve the api
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
    ports:
      - "90:80"
    depends_on:
      - app
    networks:
      - monitoring

  app:
    build: docker/php
    restart: on-failure
    volumes:
      # this will mount the api folder which contains the code to the docker container
      - ./app:/var/www/app
      # this will mount the custom `.ini` to the container
      - ./docker/php/php.${APP_ENV}.ini:/usr/local/etc/php/php.ini
    environment:
      APP_ENV: ${APP_ENV}
      API_BASE_URL: ${API_BASE_URL}
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

# volumes
volumes:
  nodemodules: {}
